--
-- File generated with SQLiteStudio v3.2.1 on Wed Dec 4 14:32:35 2019
--
-- Text encoding used: UTF-8
--
PRAGMA foreign_keys = off;
BEGIN TRANSACTION;

-- Table: batas_kategori
CREATE TABLE batas_kategori (ID_JABATAN int (11) NOT NULL, ID_KATEGORI int (11) NOT NULL, MINIMAL int (11) DEFAULT NULL, MIN_TYPE INT (1), MAKSIMAL int (11) DEFAULT NULL, MAX_TYPE INT (1), PRIMARY KEY (ID_JABATAN, ID_KATEGORI));
INSERT INTO batas_kategori (ID_JABATAN, ID_KATEGORI, MINIMAL, MIN_TYPE, MAKSIMAL, MAX_TYPE) VALUES (1, 1, NULL, NULL, NULL, NULL);
INSERT INTO batas_kategori (ID_JABATAN, ID_KATEGORI, MINIMAL, MIN_TYPE, MAKSIMAL, MAX_TYPE) VALUES (1, 2, 55, 1, NULL, NULL);
INSERT INTO batas_kategori (ID_JABATAN, ID_KATEGORI, MINIMAL, MIN_TYPE, MAKSIMAL, MAX_TYPE) VALUES (1, 3, 25, 1, NULL, NULL);
INSERT INTO batas_kategori (ID_JABATAN, ID_KATEGORI, MINIMAL, MIN_TYPE, MAKSIMAL, MAX_TYPE) VALUES (1, 4, 0.5, 0, 10, 1);
INSERT INTO batas_kategori (ID_JABATAN, ID_KATEGORI, MINIMAL, MIN_TYPE, MAKSIMAL, MAX_TYPE) VALUES (1, 5, NULL, NULL, 10, 1);
INSERT INTO batas_kategori (ID_JABATAN, ID_KATEGORI, MINIMAL, MIN_TYPE, MAKSIMAL, MAX_TYPE) VALUES (2, 1, NULL, NULL, NULL, NULL);
INSERT INTO batas_kategori (ID_JABATAN, ID_KATEGORI, MINIMAL, MIN_TYPE, MAKSIMAL, MAX_TYPE) VALUES (2, 2, 45, 1, NULL, NULL);
INSERT INTO batas_kategori (ID_JABATAN, ID_KATEGORI, MINIMAL, MIN_TYPE, MAKSIMAL, MAX_TYPE) VALUES (2, 3, 35, 1, NULL, NULL);
INSERT INTO batas_kategori (ID_JABATAN, ID_KATEGORI, MINIMAL, MIN_TYPE, MAKSIMAL, MAX_TYPE) VALUES (2, 4, 0.5, 0, 10, 1);
INSERT INTO batas_kategori (ID_JABATAN, ID_KATEGORI, MINIMAL, MIN_TYPE, MAKSIMAL, MAX_TYPE) VALUES (2, 5, NULL, NULL, 10, 1);
INSERT INTO batas_kategori (ID_JABATAN, ID_KATEGORI, MINIMAL, MIN_TYPE, MAKSIMAL, MAX_TYPE) VALUES (3, 1, NULL, NULL, NULL, NULL);
INSERT INTO batas_kategori (ID_JABATAN, ID_KATEGORI, MINIMAL, MIN_TYPE, MAKSIMAL, MAX_TYPE) VALUES (3, 2, 45, 1, NULL, NULL);
INSERT INTO batas_kategori (ID_JABATAN, ID_KATEGORI, MINIMAL, MIN_TYPE, MAKSIMAL, MAX_TYPE) VALUES (3, 3, 35, 1, NULL, NULL);
INSERT INTO batas_kategori (ID_JABATAN, ID_KATEGORI, MINIMAL, MIN_TYPE, MAKSIMAL, MAX_TYPE) VALUES (3, 4, 0.5, 0, 10, 1);
INSERT INTO batas_kategori (ID_JABATAN, ID_KATEGORI, MINIMAL, MIN_TYPE, MAKSIMAL, MAX_TYPE) VALUES (3, 5, NULL, NULL, 10, 1);
INSERT INTO batas_kategori (ID_JABATAN, ID_KATEGORI, MINIMAL, MIN_TYPE, MAKSIMAL, MAX_TYPE) VALUES (4, 1, NULL, NULL, NULL, NULL);
INSERT INTO batas_kategori (ID_JABATAN, ID_KATEGORI, MINIMAL, MIN_TYPE, MAKSIMAL, MAX_TYPE) VALUES (4, 2, 40, 1, NULL, NULL);
INSERT INTO batas_kategori (ID_JABATAN, ID_KATEGORI, MINIMAL, MIN_TYPE, MAKSIMAL, MAX_TYPE) VALUES (4, 3, 40, 1, NULL, NULL);
INSERT INTO batas_kategori (ID_JABATAN, ID_KATEGORI, MINIMAL, MIN_TYPE, MAKSIMAL, MAX_TYPE) VALUES (4, 4, 0.5, 0, 10, 1);
INSERT INTO batas_kategori (ID_JABATAN, ID_KATEGORI, MINIMAL, MIN_TYPE, MAKSIMAL, MAX_TYPE) VALUES (4, 5, NULL, NULL, 10, 1);
INSERT INTO batas_kategori (ID_JABATAN, ID_KATEGORI, MINIMAL, MIN_TYPE, MAKSIMAL, MAX_TYPE) VALUES (5, 1, NULL, NULL, NULL, NULL);
INSERT INTO batas_kategori (ID_JABATAN, ID_KATEGORI, MINIMAL, MIN_TYPE, MAKSIMAL, MAX_TYPE) VALUES (5, 2, 40, 1, NULL, NULL);
INSERT INTO batas_kategori (ID_JABATAN, ID_KATEGORI, MINIMAL, MIN_TYPE, MAKSIMAL, MAX_TYPE) VALUES (5, 3, 40, 1, NULL, NULL);
INSERT INTO batas_kategori (ID_JABATAN, ID_KATEGORI, MINIMAL, MIN_TYPE, MAKSIMAL, MAX_TYPE) VALUES (5, 4, 0.5, 0, 10, 1);
INSERT INTO batas_kategori (ID_JABATAN, ID_KATEGORI, MINIMAL, MIN_TYPE, MAKSIMAL, MAX_TYPE) VALUES (5, 5, NULL, NULL, 10, 1);
INSERT INTO batas_kategori (ID_JABATAN, ID_KATEGORI, MINIMAL, MIN_TYPE, MAKSIMAL, MAX_TYPE) VALUES (6, 1, NULL, NULL, NULL, NULL);
INSERT INTO batas_kategori (ID_JABATAN, ID_KATEGORI, MINIMAL, MIN_TYPE, MAKSIMAL, MAX_TYPE) VALUES (6, 2, 40, 1, NULL, NULL);
INSERT INTO batas_kategori (ID_JABATAN, ID_KATEGORI, MINIMAL, MIN_TYPE, MAKSIMAL, MAX_TYPE) VALUES (6, 3, 40, 1, NULL, NULL);
INSERT INTO batas_kategori (ID_JABATAN, ID_KATEGORI, MINIMAL, MIN_TYPE, MAKSIMAL, MAX_TYPE) VALUES (6, 4, 0.5, 0, 10, 1);
INSERT INTO batas_kategori (ID_JABATAN, ID_KATEGORI, MINIMAL, MIN_TYPE, MAKSIMAL, MAX_TYPE) VALUES (6, 5, NULL, NULL, 10, 1);
INSERT INTO batas_kategori (ID_JABATAN, ID_KATEGORI, MINIMAL, MIN_TYPE, MAKSIMAL, MAX_TYPE) VALUES (7, 1, NULL, NULL, NULL, NULL);
INSERT INTO batas_kategori (ID_JABATAN, ID_KATEGORI, MINIMAL, MIN_TYPE, MAKSIMAL, MAX_TYPE) VALUES (7, 2, 35, 1, NULL, NULL);
INSERT INTO batas_kategori (ID_JABATAN, ID_KATEGORI, MINIMAL, MIN_TYPE, MAKSIMAL, MAX_TYPE) VALUES (7, 3, 45, 1, NULL, NULL);
INSERT INTO batas_kategori (ID_JABATAN, ID_KATEGORI, MINIMAL, MIN_TYPE, MAKSIMAL, MAX_TYPE) VALUES (7, 4, 0.5, 0, 10, 1);
INSERT INTO batas_kategori (ID_JABATAN, ID_KATEGORI, MINIMAL, MIN_TYPE, MAKSIMAL, MAX_TYPE) VALUES (7, 5, NULL, NULL, 10, 1);
INSERT INTO batas_kategori (ID_JABATAN, ID_KATEGORI, MINIMAL, MIN_TYPE, MAKSIMAL, MAX_TYPE) VALUES (8, 1, NULL, NULL, NULL, NULL);
INSERT INTO batas_kategori (ID_JABATAN, ID_KATEGORI, MINIMAL, MIN_TYPE, MAKSIMAL, MAX_TYPE) VALUES (8, 2, 35, 1, NULL, NULL);
INSERT INTO batas_kategori (ID_JABATAN, ID_KATEGORI, MINIMAL, MIN_TYPE, MAKSIMAL, MAX_TYPE) VALUES (8, 3, 45, 1, NULL, NULL);
INSERT INTO batas_kategori (ID_JABATAN, ID_KATEGORI, MINIMAL, MIN_TYPE, MAKSIMAL, MAX_TYPE) VALUES (8, 4, 0.5, 0, 10, 1);
INSERT INTO batas_kategori (ID_JABATAN, ID_KATEGORI, MINIMAL, MIN_TYPE, MAKSIMAL, MAX_TYPE) VALUES (8, 5, NULL, NULL, 10, 1);

COMMIT TRANSACTION;
PRAGMA foreign_keys = on;
