
INSERT INTO unsur_penilaian (ID_UNSUR, ID_KATEGORI, NAMA, BATAS, UNIT, JENIS_BATAS, MAX_KREDIT, BUKTI, KETERANGAN) VALUES (1, 1, 'Mengikuti pendidikan formal dan memperoleh gelar/sebutan/ijazah : Doktor / sederajat', 1, NULL, 3, 200, 'Bukti tugas/izin belajar dan pindai ijazah asli', NULL);
INSERT INTO unsur_penilaian (ID_UNSUR, ID_KATEGORI, NAMA, BATAS, UNIT, JENIS_BATAS, MAX_KREDIT, BUKTI, KETERANGAN) VALUES (2, 1, 'Mengikuti pendidikan formal dan memperoleh gelar/sebutan/ijazah : Magister/sederajat', 1, NULL, 3, 150, 'Bukti tugas/izin belajar dan pindai ijazah asli', NULL);
INSERT INTO unsur_penilaian (ID_UNSUR, ID_KATEGORI, NAMA, BATAS, UNIT, JENIS_BATAS, MAX_KREDIT, BUKTI, KETERANGAN) VALUES (3, 1, 'Mengikuti diklat prajabatan golongan III', 1, NULL, 3, 3, 'Bukti tugas/izin belajar dan pindai ijazah asli', NULL);
INSERT INTO unsur_penilaian (ID_UNSUR, ID_KATEGORI, NAMA, BATAS, UNIT, JENIS_BATAS, MAX_KREDIT, BUKTI, KETERANGAN) VALUES (4, 2, 'Melaksanakan perkuliahan/tutorial/
perkuliahan praktikum dan membimbing,menguji serta menyelenggarakan pendidikan di laboratorium, praktik keguruan, bengkel/studio/kebun percobaan/
teknologi pengajaran dan praktik lapangan (setiap semester) : Asisten Ahli untuk :  beban mengajar 10 sks pertama', 5, NULL, 1, 0.5, 'Pindai SK penugasan asli dan bukti kinerja', NULL);
INSERT INTO unsur_penilaian (ID_UNSUR, ID_KATEGORI, NAMA, BATAS, UNIT, JENIS_BATAS, MAX_KREDIT, BUKTI, KETERANGAN) VALUES (5, 2, 'Melaksanakan perkuliahan/tutorial/
perkuliahan praktikum dan membimbing,menguji serta menyelenggarakan pendidikan di laboratorium, praktik keguruan, bengkel/studio/kebun percobaan/
teknologi pengajaran dan praktik lapangan (setiap semester) : Asisten Ahli untuk :  beban mengajar 2 sks berikutnya', '0,5', NULL, 1, 0.25, 'Pindai SK penugasan asli dan bukti kinerja', NULL);
INSERT INTO unsur_penilaian (ID_UNSUR, ID_KATEGORI, NAMA, BATAS, UNIT, JENIS_BATAS, MAX_KREDIT, BUKTI, KETERANGAN) VALUES (6, 2, 'Melaksanakan perkuliahan/tutorial/perkuliahan praktikum dan membimbing,menguji serta menyelenggarakan pendidikan di laboratorium, praktik keguruan, bengkel/studio/kebun percobaan/teknologi pengajaran dan praktik lapangan (setiap semester) : Lektor/Lektor Kepala/Profesor untuk : beban mengajar 10 sks pertama', 10, NULL, 1, 1, 'Pindai SK penugasan asli dan bukti kinerja', NULL);
INSERT INTO unsur_penilaian (ID_UNSUR, ID_KATEGORI, NAMA, BATAS, UNIT, JENIS_BATAS, MAX_KREDIT, BUKTI, KETERANGAN) VALUES (7, 2, 'Melaksanakan perkuliahan/tutorial/perkuliahan praktikum dan membimbing,menguji serta menyelenggarakan pendidikan di laboratorium, praktik keguruan, bengkel/studio/kebun percobaan/teknologi pengajaran dan praktik lapangan (setiap semester) : Lektor/Lektor Kepala/Profesor untuk : beban mengajar 2 sks berikutnya', 1, NULL, 1, 0.5, 'Pindai SK penugasan asli dan bukti kinerja', NULL);
INSERT INTO unsur_penilaian (ID_UNSUR, ID_KATEGORI, NAMA, BATAS, UNIT, JENIS_BATAS, MAX_KREDIT, BUKTI, KETERANGAN) VALUES (8, 2, 'Melaksanakan perkuliahan/tutorial/perkuliahan praktikum dan membimbing,menguji serta menyelenggarakan pendidikan di laboratorium, praktik keguruan, bengkel/studio/kebun percobaan/teknologi pengajaran dan praktik lapangan (setiap semester) : Kegiatan pelaksanaan pendidikan untuk pendidikan dokter klinis : Melakukan pengajaran untuk peserta pendidikan dokter melalui tindakan medik spesialistik', 11, NULL, 1, 4, 'Pindai SK penugasan asli dan bukti kinerja', NULL);
INSERT INTO unsur_penilaian (ID_UNSUR, ID_KATEGORI, NAMA, BATAS, UNIT, JENIS_BATAS, MAX_KREDIT, BUKTI, KETERANGAN) VALUES (9, 2, 'Melaksanakan perkuliahan/tutorial/
perkuliahan praktikum dan membimbing,menguji serta menyelenggarakan pendidikan di laboratorium, praktik keguruan, bengkel/studio/kebun percobaan/
teknologi pengajaran dan praktik lapangan (setiap semester) : Kegiatan pelaksanaan pendidikan untuk pendidikan dokter klinis : Melakukan pengajaran Konsultasi spesialis kepada peserta pendidikan dokter', 11, NULL, 1, 2, 'Pindai SK penugasan asli dan bukti kinerja', NULL);
INSERT INTO unsur_penilaian (ID_UNSUR, ID_KATEGORI, NAMA, BATAS, UNIT, JENIS_BATAS, MAX_KREDIT, BUKTI, KETERANGAN) VALUES (10, 2, 'Melaksanakan perkuliahan/tutorial/
perkuliahan praktikum dan membimbing,menguji serta menyelenggarakan pendidikan di laboratorium, praktik keguruan, bengkel/studio/kebun percobaan/
teknologi pengajaran dan praktik lapangan (setiap semester) : Kegiatan pelaksanaan pendidikan untuk pendidikan dokter klinis : Melakukan pemeriksaan luar dengan pembimbingan terhadap peserta pendidikan dokter', 11, NULL, 1, 2, 'Pindai SK penugasan asli dan bukti kinerja', NULL);
INSERT INTO unsur_penilaian (ID_UNSUR, ID_KATEGORI, NAMA, BATAS, UNIT, JENIS_BATAS, MAX_KREDIT, BUKTI, KETERANGAN) VALUES (11, 2, 'Melaksanakan perkuliahan/tutorial/
perkuliahan praktikum dan membimbing,menguji serta menyelenggarakan pendidikan di laboratorium, praktik keguruan, bengkel/studio/kebun percobaan/
teknologi pengajaran dan praktik lapangan (setiap semester) : Kegiatan pelaksanaan pendidikan untuk pendidikan dokter klinis : Melakukan pemeriksaan dalam dengan pembimbingan terhadap peserta pendidikan dokter', 11, NULL, 1, 3, 'Pindai SK penugasan asli dan bukti kinerja', NULL);
INSERT INTO unsur_penilaian (ID_UNSUR, ID_KATEGORI, NAMA, BATAS, UNIT, JENIS_BATAS, MAX_KREDIT, BUKTI, KETERANGAN) VALUES (12, 2, 'Melaksanakan perkuliahan/tutorial/
perkuliahan praktikum dan membimbing,menguji serta menyelenggarakan pendidikan di laboratorium, praktik keguruan, bengkel/studio/kebun percobaan/
teknologi pengajaran dan praktik lapangan (setiap semester) : Kegiatan pelaksanaan pendidikan untuk pendidikan dokter klinis : Menjadi saksi ahli dengan pembimbingan terhadap peserta pendidikan dokter', 11, NULL, 1, 1, 'Pindai SK penugasan asli dan bukti kinerja', NULL);
INSERT INTO unsur_penilaian (ID_UNSUR, ID_KATEGORI, NAMA, BATAS, UNIT, JENIS_BATAS, MAX_KREDIT, BUKTI, KETERANGAN) VALUES (13, 2, 'Membimbing seminar mahasiswa (setiap semester)', NULL, NULL, NULL, 1, 'Pindai SK penugasan asli dan bukti kinerja', NULL);
INSERT INTO unsur_penilaian (ID_UNSUR, ID_KATEGORI, NAMA, BATAS, UNIT, JENIS_BATAS, MAX_KREDIT, BUKTI, KETERANGAN) VALUES (14, 2, 'Membimbing KKN, Praktik Kerja Nyata, Praktik Kerja Lapangan (setiap semester)', NULL, NULL, NULL, 1, 'Pindai SK penugasan asli dan bukti kinerja', NULL);
INSERT INTO unsur_penilaian (ID_UNSUR, ID_KATEGORI, NAMA, BATAS, UNIT, JENIS_BATAS, MAX_KREDIT, BUKTI, KETERANGAN) VALUES (15, 2, 'Membimbing dan ikut membimbing dalam menghasilkan disertasi, tesis, skripsi dan laporan akhir studi yang sesuai bidang penugasannya : Pembimbing Utama per orang (setiap mahasiswa) : Disertasi', 4, 'lulusan', 1, 8, 'Pindai lembar pengesahan dan bukti kinerja', NULL);
INSERT INTO unsur_penilaian (ID_UNSUR, ID_KATEGORI, NAMA, BATAS, UNIT, JENIS_BATAS, MAX_KREDIT, BUKTI, KETERANGAN) VALUES (16, 2, 'Membimbing dan ikut membimbing dalam menghasilkan disertasi, tesis, skripsi dan laporan akhir studi yang sesuai bidang penugasannya : Pembimbing Utama per orang (setiap mahasiswa) : Tesis', 6, 'Lulusan', 1, 3, 'Pindai lembar pengesahan dan bukti kinerja', NULL);
INSERT INTO unsur_penilaian (ID_UNSUR, ID_KATEGORI, NAMA, BATAS, UNIT, JENIS_BATAS, MAX_KREDIT, BUKTI, KETERANGAN) VALUES (17, 2, 'Membimbing dan ikut membimbing dalam menghasilkan disertasi, tesis, skripsi dan laporan akhir studi yang sesuai bidang penugasannya : Pembimbing Utama per orang (setiap mahasiswa) : Skripsi', 8, 'Lulusan', 1, 1, 'Pindai lembar pengesahan dan bukti kinerja', NULL);
INSERT INTO unsur_penilaian (ID_UNSUR, ID_KATEGORI, NAMA, BATAS, UNIT, JENIS_BATAS, MAX_KREDIT, BUKTI, KETERANGAN) VALUES (18, 2, 'Membimbing dan ikut membimbing dalam menghasilkan disertasi, tesis, skripsi dan laporan akhir studi yang sesuai bidang penugasannya : Pembimbing Utama per orang (setiap mahasiswa) :  Laporan akhir studi', 10, 'Lulusan', 1, 1, 'Pindai lembar pengesahan dan bukti kinerja', NULL);
INSERT INTO unsur_penilaian (ID_UNSUR, ID_KATEGORI, NAMA, BATAS, UNIT, JENIS_BATAS, MAX_KREDIT, BUKTI, KETERANGAN) VALUES (19, 2, 'Membimbing dan ikut membimbing dalam menghasilkan disertasi, tesis, skripsi dan laporan akhir studi yang sesuai bidang penugasannya : Pembimbing Pendamping/ Pembantu per orang (setiap mhs) : Disertasi', 4, 'Lulusan', 1, 6, 'Pindai lembar pengesahan dan bukti kinerja', NULL);
INSERT INTO unsur_penilaian (ID_UNSUR, ID_KATEGORI, NAMA, BATAS, UNIT, JENIS_BATAS, MAX_KREDIT, BUKTI, KETERANGAN) VALUES (20, 2, 'Membimbing dan ikut membimbing dalam menghasilkan disertasi, tesis, skripsi dan laporan akhir studi yang sesuai bidang penugasannya : Pembimbing Pendamping/ Pembantu per orang (setiap mhs) : Tesis', 6, 'Lulusan', 1, 2, 'Pindai lembar pengesahan dan bukti kinerja', NULL);
INSERT INTO unsur_penilaian (ID_UNSUR, ID_KATEGORI, NAMA, BATAS, UNIT, JENIS_BATAS, MAX_KREDIT, BUKTI, KETERANGAN) VALUES (21, 2, 'Membimbing dan ikut membimbing dalam menghasilkan disertasi, tesis, skripsi dan laporan akhir studi yang sesuai bidang penugasannya : Pembimbing Pendamping/ Pembantu per orang (setiap mhs) : Skripsi', 8, 'Lulusan', 1, 0.5, 'Pindai lembar pengesahan dan bukti kinerja', NULL);
INSERT INTO unsur_penilaian (ID_UNSUR, ID_KATEGORI, NAMA, BATAS, UNIT, JENIS_BATAS, MAX_KREDIT, BUKTI, KETERANGAN) VALUES (22, 2, 'Membimbing dan ikut membimbing dalam menghasilkan disertasi, tesis, skripsi dan laporan akhir studi yang sesuai bidang penugasannya : Pembimbing Pendamping/ Pembantu per orang (setiap mhs) : Laporan akhir studi', 10, 'Lulusan', 1, 0.5, 'Pindai lembar pengesahan dan bukti kinerja', NULL);
INSERT INTO unsur_penilaian (ID_UNSUR, ID_KATEGORI, NAMA, BATAS, UNIT, JENIS_BATAS, MAX_KREDIT, BUKTI, KETERANGAN) VALUES (23, 2, 'Bertugas sebagai penguji pada ujian akhir/Profesi* (setiap mahasiswa) : Ketua Penguji', 4, 'Lulusan', 1, 1, 'Pindai SK penugasan, bukti kinerja dan undangan', NULL);
INSERT INTO unsur_penilaian (ID_UNSUR, ID_KATEGORI, NAMA, BATAS, UNIT, JENIS_BATAS, MAX_KREDIT, BUKTI, KETERANGAN) VALUES (24, 2, 'Bertugas sebagai penguji pada ujian akhir/Profesi* (setiap mahasiswa) : Anggota Penguji', 8, 'Lulusan', 1, 0.5, 'Pindai SK penugasan, bukti kinerja dan undangan', NULL);
INSERT INTO unsur_penilaian (ID_UNSUR, ID_KATEGORI, NAMA, BATAS, UNIT, JENIS_BATAS, MAX_KREDIT, BUKTI, KETERANGAN) VALUES (25, 2, 'Membina kegiatan mahasiswa di bidang akademik dan kemahasiswaan, termasuk dalam kegiatan ini adalah membimbing mahasiswa menghasilkan produk saintifik (setiap semester)', 2, 'Kegiatan', 1, 2, 'Pindai SK penugasan, dan bukti kinerja', NULL);
INSERT INTO unsur_penilaian (ID_UNSUR, ID_KATEGORI, NAMA, BATAS, UNIT, JENIS_BATAS, MAX_KREDIT, BUKTI, KETERANGAN) VALUES (26, 2, 'Mengembangkan program kuliah yang mempunyai nilai kebaharuan metode atau substansi (setiap produk)', 1, 'Mata Kuliah', 1, 2, 'File produk', NULL);
INSERT INTO unsur_penilaian (ID_UNSUR, ID_KATEGORI, NAMA, BATAS, UNIT, JENIS_BATAS, MAX_KREDIT, BUKTI, KETERANGAN) VALUES (27, 2, 'Mengembangkan bahan pengajaran/ bahan kuliah yang mempunyai nilai kebaharuan (setiap produk) : Buku ajar', 1, 'buku', 2, 20, 'File produk', NULL);
INSERT INTO unsur_penilaian (ID_UNSUR, ID_KATEGORI, NAMA, BATAS, UNIT, JENIS_BATAS, MAX_KREDIT, BUKTI, KETERANGAN) VALUES (28, 2, 'Mengembangkan bahan pengajaran/ bahan kuliah yang mempunyai nilai kebaharuan (setiap produk), : Diktat,Modul, Petunjuk praktikum, Model, Alat bantu, Audio visual, Naskah tutorial, Job sheet praktikum terkait dengan mata kuliah yang diampu', 1, 'Produk', 1, 5, 'File produk', NULL);
INSERT INTO unsur_penilaian (ID_UNSUR, ID_KATEGORI, NAMA, BATAS, UNIT, JENIS_BATAS, MAX_KREDIT, BUKTI, KETERANGAN) VALUES (29, 2, 'Menyampaikan orasi ilmiah di tingkat perguruan tinggi', 2, 'Orasi', 1, 5, 'File produk', NULL);
INSERT INTO unsur_penilaian (ID_UNSUR, ID_KATEGORI, NAMA, BATAS, UNIT, JENIS_BATAS, MAX_KREDIT, BUKTI, KETERANGAN) VALUES (30, 2, 'Menduduki jabatan pimpinan perguruan tinggi sesuai tugas pokok, fungsi dan kewenangan dan/atau setara (setiap semester) : Rektor', 1, 'Jabatan', 1, 6, 'Pindai SK Jabatan', NULL);
INSERT INTO unsur_penilaian (ID_UNSUR, ID_KATEGORI, NAMA, BATAS, UNIT, JENIS_BATAS, MAX_KREDIT, BUKTI, KETERANGAN) VALUES (31, 2, 'Menduduki jabatan pimpinan perguruan tinggi sesuai tugas pokok, fungsi dan kewenangan dan/atau setara (setiap semester) : Wakil rektor/dekan/direktur program pasca sarjana/ketua lembaga', 1, 'Jabatan', 1, 5, 'Pindai SK Jabatan', NULL);
INSERT INTO unsur_penilaian (ID_UNSUR, ID_KATEGORI, NAMA, BATAS, UNIT, JENIS_BATAS, MAX_KREDIT, BUKTI, KETERANGAN) VALUES (32, 2, 'Menduduki jabatan pimpinan perguruan tinggi sesuai tugas pokok, fungsi dan kewenangan dan/atau setara (setiap semester) : Ketua sekolah tinggi/pembantu dekan/asisten direktur program pasca sarjana/direktur politeknik/kepala LLDikti', 1, 'Jabatan', 1, 4, 'Pindai SK Jabatan', NULL);
INSERT INTO unsur_penilaian (ID_UNSUR, ID_KATEGORI, NAMA, BATAS, UNIT, JENIS_BATAS, MAX_KREDIT, BUKTI, KETERANGAN) VALUES (33, 2, 'Menduduki jabatan pimpinan perguruan tinggi sesuai tugas pokok, fungsi dan kewenangan dan/atau setara (setiap semester) : Pembantu ketua sekolah tinggi/pembantu direktur politeknik', 1, 'Jabatan', 1, 4, 'Pindai SK Jabatan', NULL);
INSERT INTO unsur_penilaian (ID_UNSUR, ID_KATEGORI, NAMA, BATAS, UNIT, JENIS_BATAS, MAX_KREDIT, BUKTI, KETERANGAN) VALUES (34, 2, 'Menduduki jabatan pimpinan perguruan tinggi sesuai tugas pokok, fungsi dan kewenangan dan/atau setara (setiap semester) : Direktur akademi', 1, 'Jabatan', 1, 4, 'Pindai SK Jabatan', NULL);
INSERT INTO unsur_penilaian (ID_UNSUR, ID_KATEGORI, NAMA, BATAS, UNIT, JENIS_BATAS, MAX_KREDIT, BUKTI, KETERANGAN) VALUES (35, 2, 'Menduduki jabatan pimpinan perguruan tinggi sesuai tugas pokok, fungsi dan kewenangan dan/atau setara (setiap semester) : Pembantu direktur politeknik, ketua jurusan/ bagian pada universitas/ institut/sekolah tinggi', 1, 'Jabatan', 1, 3, 'Pindai SK Jabatan', NULL);
INSERT INTO unsur_penilaian (ID_UNSUR, ID_KATEGORI, NAMA, BATAS, UNIT, JENIS_BATAS, MAX_KREDIT, BUKTI, KETERANGAN) VALUES (36, 2, 'Menduduki jabatan pimpinan perguruan tinggi sesuai tugas pokok, fungsi dan kewenangan dan/atau setara (setiap semester) : Pembantu direktur akademi/ketua jurusan/ketua prodi pada universitas /politeknik/akademi, sekretaris jurusan/bagian pada universitas /institut/sekolah tinggi', 1, 'Jabatan', 1, 3, 'Pindai SK Jabatan', NULL);
INSERT INTO unsur_penilaian (ID_UNSUR, ID_KATEGORI, NAMA, BATAS, UNIT, JENIS_BATAS, MAX_KREDIT, BUKTI, KETERANGAN) VALUES (37, 2, 'Menduduki jabatan pimpinan perguruan tinggi sesuai tugas pokok, fungsi dan kewenangan dan/atau setara (setiap semester) : Sekretaris jurusan pada politeknik/akademi dan kepala laboratorium (bengkel) universitas/institut/sekolah tinggi/politeknik/akademi', 1, 'Jabatan', 1, 3, 'Pindai SK Jabatan', NULL);
INSERT INTO unsur_penilaian (ID_UNSUR, ID_KATEGORI, NAMA, BATAS, UNIT, JENIS_BATAS, MAX_KREDIT, BUKTI, KETERANGAN) VALUES (38, 2, 'Membimbing dosen yang mempunyai jabatan akademik lebih rendah setiap semester (bagi dosen Lektor Kepala ke atas) : Pembimbing pencangkokan', 1, 'Orang', NULL, 2, 'Pindai SK Penugasan, dan bukti kinerja', NULL);
INSERT INTO unsur_penilaian (ID_UNSUR, ID_KATEGORI, NAMA, BATAS, UNIT, JENIS_BATAS, MAX_KREDIT, BUKTI, KETERANGAN) VALUES (39, 2, 'Membimbing dosen yang mempunyai jabatan akademik lebih rendah setiap semester (bagi dosen Lektor Kepala ke atas) : Reguler', 1, 'Orang', NULL, 1, 'Pindai SK Penugasan, dan bukti kinerja', NULL);
INSERT INTO unsur_penilaian (ID_UNSUR, ID_KATEGORI, NAMA, BATAS, UNIT, JENIS_BATAS, MAX_KREDIT, BUKTI, KETERANGAN) VALUES (40, 2, 'Melaksanakan kegiatan detasering dan pencangkokan di luar institusi tempat bekerja setiap semester (bagi dosen Lektor kepala ke atas) : Detasering', 1, 'Orang', NULL, 5, 'Pindai SK Penugasan, dan bukti kinerja', NULL);
INSERT INTO unsur_penilaian (ID_UNSUR, ID_KATEGORI, NAMA, BATAS, UNIT, JENIS_BATAS, MAX_KREDIT, BUKTI, KETERANGAN) VALUES (41, 2, 'Melaksanakan kegiatan detasering dan pencangkokan di luar institusi tempat bekerja setiap semester (bagi dosen Lektor kepala ke atas) : Pencangkokan', 1, 'Orang', NULL, 4, 'Pindai SK Penugasan, dan bukti kinerja', NULL);
INSERT INTO unsur_penilaian (ID_UNSUR, ID_KATEGORI, NAMA, BATAS, UNIT, JENIS_BATAS, MAX_KREDIT, BUKTI, KETERANGAN) VALUES (42, 2, 'Melaksanakan pengembangan diri untuk meningkatkan kompetensi : Lamanya lebih dari 960 jam', NULL, NULL, NULL, 15, 'Pindai sertifikat asli', NULL);
INSERT INTO unsur_penilaian (ID_UNSUR, ID_KATEGORI, NAMA, BATAS, UNIT, JENIS_BATAS, MAX_KREDIT, BUKTI, KETERANGAN) VALUES (43, 2, 'Melaksanakan pengembangan diri untuk meningkatkan kompetensi : Lamanya antara 641- 960 jam', NULL, NULL, NULL, 9, 'Pindai sertifikat asli', NULL);
INSERT INTO unsur_penilaian (ID_UNSUR, ID_KATEGORI, NAMA, BATAS, UNIT, JENIS_BATAS, MAX_KREDIT, BUKTI, KETERANGAN) VALUES (44, 2, 'Melaksanakan pengembangan diri untuk meningkatkan kompetensi : Lamanya antara 481- 640 jam', NULL, NULL, NULL, 6, 'Pindai sertifikat asli', NULL);
INSERT INTO unsur_penilaian (ID_UNSUR, ID_KATEGORI, NAMA, BATAS, UNIT, JENIS_BATAS, MAX_KREDIT, BUKTI, KETERANGAN) VALUES (45, 2, 'Melaksanakan pengembangan diri untuk meningkatkan kompetensi : Lamanya antara 161- 480 jam', NULL, NULL, NULL, 3, 'Pindai sertifikat asli', NULL);
INSERT INTO unsur_penilaian (ID_UNSUR, ID_KATEGORI, NAMA, BATAS, UNIT, JENIS_BATAS, MAX_KREDIT, BUKTI, KETERANGAN) VALUES (46, 2, 'Melaksanakan pengembangan diri untuk meningkatkan kompetensi : Lamanya antara 81- 160 jam', NULL, NULL, NULL, 2, 'Pindai sertifikat asli', NULL);
INSERT INTO unsur_penilaian (ID_UNSUR, ID_KATEGORI, NAMA, BATAS, UNIT, JENIS_BATAS, MAX_KREDIT, BUKTI, KETERANGAN) VALUES (47, 2, 'Melaksanakan pengembangan diri untuk meningkatkan kompetensi : Lamanya antara 30 - 80 jam', NULL, NULL, NULL, 1, 'Pindai sertifikat asli', NULL);
INSERT INTO unsur_penilaian (ID_UNSUR, ID_KATEGORI, NAMA, BATAS, UNIT, JENIS_BATAS, MAX_KREDIT, BUKTI, KETERANGAN) VALUES (48, 2, 'Melaksanakan pengembangan diri untuk meningkatkan kompetensi : Lamanya antara 10 - 30 jam', NULL, NULL, NULL, 0.5, 'Pindai sertifikat asli', NULL);
INSERT INTO unsur_penilaian (ID_UNSUR, ID_KATEGORI, NAMA, BATAS, UNIT, JENIS_BATAS, MAX_KREDIT, BUKTI, KETERANGAN) VALUES (49, 3, 'Menghasilkan karya ilmiah sesuai dengan bidang ilmunya : Hasil penelitian atau hasil pemikiran yang dipublikasikan dalam bentuk buku : Buku referensi', 1, 'Buku', 2, 40, 'Pindai halaman sampul, dan bukti kinerja', NULL);
INSERT INTO unsur_penilaian (ID_UNSUR, ID_KATEGORI, NAMA, BATAS, UNIT, JENIS_BATAS, MAX_KREDIT, BUKTI, KETERANGAN) VALUES (50, 3, 'Menghasilkan karya ilmiah sesuai dengan bidang ilmunya : Hasil penelitian atau hasil pemikiran yang dipublikasikan dalam bentuk buku : Monograf', 1, 'Buku', 2, 20, 'Pindai halaman sampul dan bukti kinerja', NULL);
INSERT INTO unsur_penilaian (ID_UNSUR, ID_KATEGORI, NAMA, BATAS, UNIT, JENIS_BATAS, MAX_KREDIT, BUKTI, KETERANGAN) VALUES (51, 3, 'Menghasilkan karya ilmiah sesuai dengan bidang ilmunya : Hasil penelitian atau hasil pemikiran dalam buku yang dipublikasikan dan berisi berbagai tulisan dari berbagai penulis (book chapter) : Internasional', 1, 'Buku', 2, 15, 'Pindai halaman sampul, daftar isi dan bukti kinerja', NULL);
INSERT INTO unsur_penilaian (ID_UNSUR, ID_KATEGORI, NAMA, BATAS, UNIT, JENIS_BATAS, MAX_KREDIT, BUKTI, KETERANGAN) VALUES (52, 3, 'Menghasilkan karya ilmiah sesuai dengan bidang ilmunya : Hasil penelitian atau hasil pemikiran dalam buku yang dipublikasikan dan berisi berbagai tulisan dari berbagai penulis (book chapter) : Nasional', 1, 'Buku', 2, 10, 'Pindai halaman sampul, daftar isi dan bukti kinerja', NULL);
INSERT INTO unsur_penilaian (ID_UNSUR, ID_KATEGORI, NAMA, BATAS, UNIT, JENIS_BATAS, MAX_KREDIT, BUKTI, KETERANGAN) VALUES (53, 3, 'Menghasilkan karya ilmiah sesuai dengan bidang ilmunya : Hasil penelitian atau hasil pemikiran yang dipublikasikan : Jurnal internasional bereputasi (terindeks pada database internasional bereputasi dan berfaktor dampak)', NULL, NULL, NULL, 40, 'Pindai halaman sampul, daftar isi, dewan redaksi/redaksi pelaksana dan bukti kinerja', 'Penjelasan Butir 12.2 Untuk pemenuhan persyaratan khusus');
INSERT INTO unsur_penilaian (ID_UNSUR, ID_KATEGORI, NAMA, BATAS, UNIT, JENIS_BATAS, MAX_KREDIT, BUKTI, KETERANGAN) VALUES (54, 3, 'Menghasilkan karya ilmiah sesuai dengan bidang ilmunya : Hasil penelitian atau hasil pemikiran yang dipublikasikan : Jurnal internasional terindeks pada basis data internasional bereputasi', NULL, NULL, NULL, 30, 'Pindai halaman sampul, daftar isi,dewan redaksi/redaksi pelaksana dan bukti kinerja', 'Penjelasan Butir 12.1 Untuk pemenuhan persyaratan khusus');
INSERT INTO unsur_penilaian (ID_UNSUR, ID_KATEGORI, NAMA, BATAS, UNIT, JENIS_BATAS, MAX_KREDIT, BUKTI, KETERANGAN) VALUES (55, 3, 'Menghasilkan karya ilmiah sesuai dengan bidang ilmunya : Hasil penelitian atau hasil pemikiran yang dipublikasikan : Jurnal internasional terindeks pada basis data internasional di luar kategori 2)', NULL, NULL, NULL, 20, 'Pindai halaman sampul, daftar isi, redaksi pelaksana dan bukti kinerja', 'Termasuk jurnal terindeks di Web of Science Clarivate Analytics Kelompok Emerging Sources Citation Index (ESCI)');
INSERT INTO unsur_penilaian (ID_UNSUR, ID_KATEGORI, NAMA, BATAS, UNIT, JENIS_BATAS, MAX_KREDIT, BUKTI, KETERANGAN) VALUES (56, 3, 'Menghasilkan karya ilmiah sesuai dengan bidang ilmunya : Hasil penelitian atau hasil pemikiran yang dipublikasikan :   Jurnal Nasional terakreditasi Dikti', NULL, NULL, NULL, 25, 'Pindai halaman sampul, daftar isi, dewan redaksi/redaksi pelaksana  dan bukti kinerja', NULL);
INSERT INTO unsur_penilaian (ID_UNSUR, ID_KATEGORI, NAMA, BATAS, UNIT, JENIS_BATAS, MAX_KREDIT, BUKTI, KETERANGAN) VALUES (57, 3, 'Menghasilkan karya ilmiah sesuai dengan bidang ilmunya : Hasil penelitian atau hasil pemikiran yang dipublikasikan :  Jurnal nasional terakreditasi Kemenristekdikti peringkat 1 dan 2', NULL, NULL, NULL, 25, 'Pindai halaman sampul, daftar isi, dewan redaksi/redaksi pelaksana  dan bukti kinerja', NULL);
INSERT INTO unsur_penilaian (ID_UNSUR, ID_KATEGORI, NAMA, BATAS, UNIT, JENIS_BATAS, MAX_KREDIT, BUKTI, KETERANGAN) VALUES (58, 3, 'Menghasilkan karya ilmiah sesuai dengan bidang ilmunya : Hasil penelitian atau hasil pemikiran yang dipublikasikan :  Jurnal Nasional berbahasa
Inggris atau bahasa resmi (PBB) terindeks pada basis data yang diakui Kemenristekdikti, contohnya: CABI atau Index Copernicus International (ICI).', NULL, NULL, NULL, 20, 'Pindai halaman sampul, dewan
redaksi/ redaksi pelaksana ,daftar isi dan bukti kinerja', NULL);
INSERT INTO unsur_penilaian (ID_UNSUR, ID_KATEGORI, NAMA, BATAS, UNIT, JENIS_BATAS, MAX_KREDIT, BUKTI, KETERANGAN) VALUES (59, 3, 'Menghasilkan karya ilmiah sesuai dengan bidang ilmunya : Hasil penelitian atau hasil pemikiran yang dipublikasikan :   Jurnal nasional terakreditasi peringkat 3 dan 4', NULL, NULL, NULL, 20, 'Pindai halaman sampul, dewan
redaksi/ redaksi pelaksana ,daftar isi dan bukti kinerja', NULL);
INSERT INTO unsur_penilaian (ID_UNSUR, ID_KATEGORI, NAMA, BATAS, UNIT, JENIS_BATAS, MAX_KREDIT, BUKTI, KETERANGAN) VALUES (60, 3, 'Menghasilkan karya ilmiah sesuai dengan bidang ilmunya : Hasil penelitian atau hasil pemikiran yang dipublikasikan :  Jurnal Nasional berbahasa Indonesia terindeks pada basis data yang diakui Kemenristekdikti, contohnya : akreditasi peringkat 5 dan 6', NULL, NULL, NULL, 15, 'Pindai halaman sampul, dewan
redaksi/ redaksi pelaksana ,daftar isi dan bukti kinerja', NULL);
INSERT INTO unsur_penilaian (ID_UNSUR, ID_KATEGORI, NAMA, BATAS, UNIT, JENIS_BATAS, MAX_KREDIT, BUKTI, KETERANGAN) VALUES (61, 3, 'Menghasilkan karya ilmiah sesuai dengan bidang ilmunya : Hasil penelitian atau hasil pemikiran yang dipublikasikan :  Jurnal Nasional', 25, '%', 4, 10, 'Pindai halaman sampul, dewan
redaksi/ redaksi pelaksana ,daftar isi dan bukti kinerja', NULL);
INSERT INTO unsur_penilaian (ID_UNSUR, ID_KATEGORI, NAMA, BATAS, UNIT, JENIS_BATAS, MAX_KREDIT, BUKTI, KETERANGAN) VALUES (62, 3, 'Menghasilkan karya ilmiah sesuai dengan bidang ilmunya : Hasil penelitian atau hasil pemikiran yang dipublikasikan :  Jurnal ilmiah yang ditulis dalam Bahasa Resmi PBB namun tidak memenuhi syarat-syarat sebagai jurnal ilmiah internasional', NULL, NULL, NULL, 10, 'Pindai halaman sampul, dewan
redaksi/ redaksi pelaksana ,daftar isi dan bukti kinerja', NULL);
INSERT INTO unsur_penilaian (ID_UNSUR, ID_KATEGORI, NAMA, BATAS, UNIT, JENIS_BATAS, MAX_KREDIT, BUKTI, KETERANGAN) VALUES (63, 3, 'Hasil penelitian atau hasil pemikiran yang didesiminasikan :', 25, '%', 5, '', NULL, NULL);
INSERT INTO unsur_penilaian (ID_UNSUR, ID_KATEGORI, NAMA, BATAS, UNIT, JENIS_BATAS, MAX_KREDIT, BUKTI, KETERANGAN) VALUES (64, 3, 'Hasil penelitian atau hasil pemikiran yang didesiminasikan : Dipresentasikan secara oral dan dimuat dalam prosiding yang dipublikasikan (ber ISSN/ISBN) : Internasional terindeks pada Scimagojr dan Scopus', NULL, NULL, NULL, 30, 'Pindai halaman sampul, Panitia pelaksana, Panitia pengarah, daftar isi dan bukti kinerja', NULL);
INSERT INTO unsur_penilaian (ID_UNSUR, ID_KATEGORI, NAMA, BATAS, UNIT, JENIS_BATAS, MAX_KREDIT, BUKTI, KETERANGAN) VALUES (65, 3, 'Hasil penelitian atau hasil pemikiran yang didesiminasikan : Dipresentasikan secara oral dan dimuat dalam prosiding yang dipublikasikan (ber ISSN/ISBN) : Internasional terindeks pada SCOPUS, IEEE Explore, SPIE', NULL, NULL, NULL, 25, 'Pindai halaman sampul, Panitia pelaksana, Panitia pengarah, daftar isi dan bukti kinerja', NULL);
INSERT INTO unsur_penilaian (ID_UNSUR, ID_KATEGORI, NAMA, BATAS, UNIT, JENIS_BATAS, MAX_KREDIT, BUKTI, KETERANGAN) VALUES (66, 3, 'Hasil penelitian atau hasil pemikiran yang didesiminasikan : Dipresentasikan secara oral dan dimuat dalam prosiding yang dipublikasikan (ber ISSN/ISBN) : Internasional', NULL, NULL, NULL, 15, 'Pindai halaman sampul, Panitia pelaksana, Panitia pengarah, daftar isi dan bukti kinerja', NULL);
INSERT INTO unsur_penilaian (ID_UNSUR, ID_KATEGORI, NAMA, BATAS, UNIT, JENIS_BATAS, MAX_KREDIT, BUKTI, KETERANGAN) VALUES (67, 3, 'Hasil penelitian atau hasil pemikiran yang didesiminasikan : Dipresentasikan secara oral dan dimuat dalam prosiding yang dipublikasikan (ber ISSN/ISBN) : Nasional', NULL, NULL, NULL, 10, 'Pindai halaman sampul, Panitia Pelaksana, Panitia pengarah, daftar isi dan bukti kinerja', NULL);
INSERT INTO unsur_penilaian (ID_UNSUR, ID_KATEGORI, NAMA, BATAS, UNIT, JENIS_BATAS, MAX_KREDIT, BUKTI, KETERANGAN) VALUES (68, 3, 'Hasil penelitian atau hasil pemikiran yang didesiminasikan : Disajikan dalam bentuk poster dan dimuat dalam prosiding yang dipublikasikan: Internasional', NULL, NULL, NULL, 10, 'Pindai poster, Panitia Pelaksana, Panitia Pengarah daftar isi dan buku panduan', NULL);
INSERT INTO unsur_penilaian (ID_UNSUR, ID_KATEGORI, NAMA, BATAS, UNIT, JENIS_BATAS, MAX_KREDIT, BUKTI, KETERANGAN) VALUES (69, 3, 'Hasil penelitian atau hasil pemikiran yang didesiminasikan : Disajikan dalam bentuk poster dan dimuat dalam prosiding yang dipublikasikan : Nasional', NULL, NULL, NULL, 5, 'Pindai poster, Panitia Pelaksana, Panitia pengarah, daftar isi dan bukun panduan', NULL);
INSERT INTO unsur_penilaian (ID_UNSUR, ID_KATEGORI, NAMA, BATAS, UNIT, JENIS_BATAS, MAX_KREDIT, BUKTI, KETERANGAN) VALUES (70, 3, 'Hasil penelitian atau hasil pemikiran yang didesiminasikan : Disajikan dalam seminar/simposium/ lokakarya, tetapi tidak dimuat dalam prosiding yang dipublikasikan : Internasional', NULL, NULL, NULL, 5, 'Pindai bukti kehadiran atau sertifikat dan bukti kinerja, Panitia', NULL);
INSERT INTO unsur_penilaian (ID_UNSUR, ID_KATEGORI, NAMA, BATAS, UNIT, JENIS_BATAS, MAX_KREDIT, BUKTI, KETERANGAN) VALUES (71, 3, 'Hasil penelitian atau hasil pemikiran yang didesiminasikan : Disajikan dalam seminar/simposium/ lokakarya, tetapi tidak dimuat dalam prosiding yang dipublikasikan : Nasional', NULL, NULL, NULL, 3, 'Pindai bukti kehadiran atau sertifikat dan bukti kinerja', NULL);
INSERT INTO unsur_penilaian (ID_UNSUR, ID_KATEGORI, NAMA, BATAS, UNIT, JENIS_BATAS, MAX_KREDIT, BUKTI, KETERANGAN) VALUES (72, 3, 'Hasil penelitian atau hasil pemikiran yang didesiminasikan : Hasil penelitian/pemikiran yang tidak disajikan dalam seminar/simposium/ lokakarya, tetapi dimuat dalam prosiding : Internasional', NULL, NULL, NULL, 10, 'Pindai halaman sampul, daftar isi makalah, dan bukti kinerja', NULL);
INSERT INTO unsur_penilaian (ID_UNSUR, ID_KATEGORI, NAMA, BATAS, UNIT, JENIS_BATAS, MAX_KREDIT, BUKTI, KETERANGAN) VALUES (73, 3, 'Hasil penelitian atau hasil pemikiran yang didesiminasikan : Hasil penelitian/pemikiran yang tidak disajikan dalam seminar/simposium/ lokakarya, tetapi dimuat dalam prosiding : Nasional', NULL, NULL, NULL, 5, 'Pindai halaman sampul, daftar isi makalah, dan bukti kinerja', NULL);
INSERT INTO unsur_penilaian (ID_UNSUR, ID_KATEGORI, NAMA, BATAS, UNIT, JENIS_BATAS, MAX_KREDIT, BUKTI, KETERANGAN) VALUES (74, 3, 'Hasil penelitian atau hasil pemikiran yang didesiminasikan : Hasil penelitian/pemikiran yang disajikan dalam koran/majalah populer/umum', 5, '%', 6, 1, 'Pindai halaman sampul dan bukti kinerja', NULL);
INSERT INTO unsur_penilaian (ID_UNSUR, ID_KATEGORI, NAMA, BATAS, UNIT, JENIS_BATAS, MAX_KREDIT, BUKTI, KETERANGAN) VALUES (75, 3, 'Hasil penelitian atau pemikiran atau kerjasama industri yang tidak dipublikasikan (tersimpan dalam perpustakaan) yang dilakukan secara melembaga', 5, '%', 6, 2, 'Pindai halaman sampul, daftar isi, lembar pengesahan dan bukti kinerja', NULL);
INSERT INTO unsur_penilaian (ID_UNSUR, ID_KATEGORI, NAMA, BATAS, UNIT, JENIS_BATAS, MAX_KREDIT, BUKTI, KETERANGAN) VALUES (76, 3, 'Menerjemahkan/menyadur buku ilmiah yang diterbitkan (ber ISBN)', NULL, NULL, NULL, 15, 'Pindai halaman sampul dan bukti kinerja yang dapat diakses oleh asesor', NULL);
INSERT INTO unsur_penilaian (ID_UNSUR, ID_KATEGORI, NAMA, BATAS, UNIT, JENIS_BATAS, MAX_KREDIT, BUKTI, KETERANGAN) VALUES (77, 3, 'Mengedit/menyunting karya ilmiah dalam bentuk buku yang diterbitkan (ber ISBN)', NULL, NULL, NULL, 10, 'Pindai halaman sampul dan bukti kinerja yang dapat diakses oleh asesor', NULL);
INSERT INTO unsur_penilaian (ID_UNSUR, ID_KATEGORI, NAMA, BATAS, UNIT, JENIS_BATAS, MAX_KREDIT, BUKTI, KETERANGAN) VALUES (78, 3, 'Membuat rancangan dan karya teknologi yang dipatenkan atau seni yang terdaftar di HaKI secara nasional atau internasional : Internasional yang sudah diimplementasikan di industri (paling sedikit diakui oleh 4 Negara)', NULL, NULL, NULL, 60, 'Pindai bukti kinerja dan sertifikat paten', NULL);
INSERT INTO unsur_penilaian (ID_UNSUR, ID_KATEGORI, NAMA, BATAS, UNIT, JENIS_BATAS, MAX_KREDIT, BUKTI, KETERANGAN) VALUES (79, 3, 'Membuat rancangan dan karya teknologi yang dipatenkan atau seni yang terdaftar di HaKI secara nasional atau internasional : Internasional (paling sedikit diakui oleh 4 Negara)', NULL, NULL, NULL, 50, 'Pindai bukti kinerja dan sertifikat paten', NULL);
INSERT INTO unsur_penilaian (ID_UNSUR, ID_KATEGORI, NAMA, BATAS, UNIT, JENIS_BATAS, MAX_KREDIT, BUKTI, KETERANGAN) VALUES (80, 3, 'Membuat rancangan dan karya teknologi yang dipatenkan atau seni yang terdaftar di HaKI secara nasional atau internasional : Nasional (yang sudah diimplementasikan di industri)', NULL, NULL, NULL, 40, 'Pindai bukti kinerja dan sertifikat paten', NULL);
INSERT INTO unsur_penilaian (ID_UNSUR, ID_KATEGORI, NAMA, BATAS, UNIT, JENIS_BATAS, MAX_KREDIT, BUKTI, KETERANGAN) VALUES (81, 3, 'Membuat rancangan dan karya teknologi yang dipatenkan atau seni yang terdaftar di HaKI secara nasional atau internasional : Nasional', NULL, NULL, NULL, 30, 'Pindai bukti kinerja dan sertifikat paten', NULL);
INSERT INTO unsur_penilaian (ID_UNSUR, ID_KATEGORI, NAMA, BATAS, UNIT, JENIS_BATAS, MAX_KREDIT, BUKTI, KETERANGAN) VALUES (82, 3, 'Membuat rancangan dan karya teknologi yang dipatenkan atau seni yang terdaftar di HaKI secara nasional atau internasional : Nasional, dalam bentuk paten sederhana yang telah memiliki sertifikat dari Direktorat Jenderal Kekayaan Intelektual, Kemenkumham;', NULL, NULL, NULL, 20, 'Pindai bukti kinerja dan sertifikat paten', NULL);
INSERT INTO unsur_penilaian (ID_UNSUR, ID_KATEGORI, NAMA, BATAS, UNIT, JENIS_BATAS, MAX_KREDIT, BUKTI, KETERANGAN) VALUES (83, 3, 'Membuat rancangan dan karya teknologi yang dipatenkan atau seni yang terdaftar di HaKI secara nasional atau internasional : Karya ciptaan, desain industri, indikasi geografis yang telah memiliki sertifikat dari Direktorat Jenderal Kekayaan Intelektual, Kemenkumham; Karya cipta berupa buku yang telah mendapatkan sertifikat karya cipta dari Direktorat Jenderal Kekayaan Intelektual, Kemenkumham maka karya cipta tersebut hanya dapat diajukan salah satu sebagai bukti melaksanakan penelitian atau pendidikan.', 2, 'Karya', 1, 15, 'Pindai bukti kinerja dan sertifikat dari Direktorat Jenderal Kekayaan Intelektual, Kemenkumham', NULL);
INSERT INTO unsur_penilaian (ID_UNSUR, ID_KATEGORI, NAMA, BATAS, UNIT, JENIS_BATAS, MAX_KREDIT, BUKTI, KETERANGAN) VALUES (84, 3, 'Membuat rancangan dan karya teknologi yang tidak dipatenkan; rancangan dan karya seni monumental yang tidak terdaftar di HaKI tetapi telah dipresentasikan pada forum yang teragenda : Tingkat Internasional', NULL, NULL, NULL, 20, 'Pindai bukti kinerja, peer review internasional  sesuai bidang ilmu', NULL);
INSERT INTO unsur_penilaian (ID_UNSUR, ID_KATEGORI, NAMA, BATAS, UNIT, JENIS_BATAS, MAX_KREDIT, BUKTI, KETERANGAN) VALUES (85, 3, 'Membuat rancangan dan karya teknologi yang tidak dipatenkan; rancangan dan karya seni monumental yang tidak terdaftar di HaKI tetapi telah dipresentasikan pada forum yang teragenda : Tingkat Nasional', NULL, NULL, NULL, 15, 'Pindai bukti kinerja, peer review sesuai bidang ilmu', NULL);
INSERT INTO unsur_penilaian (ID_UNSUR, ID_KATEGORI, NAMA, BATAS, UNIT, JENIS_BATAS, MAX_KREDIT, BUKTI, KETERANGAN) VALUES (86, 3, 'Membuat rancangan dan karya teknologi yang tidak dipatenkan; rancangan dan karya seni monumental yang tidak terdaftar di HaKI tetapi telah dipresentasikan pada forum yang teragenda : Tingkat Lokal', NULL, NULL, NULL, 10, 'Pindai bukti kinerja, peer review sesuai bidang ilmu', NULL);
INSERT INTO unsur_penilaian (ID_UNSUR, ID_KATEGORI, NAMA, BATAS, UNIT, JENIS_BATAS, MAX_KREDIT, BUKTI, KETERANGAN) VALUES (87, 3, 'Pelaksanaan penelitian karya seni sebagai komposer/penulis naskah/sutradara/perancang/pencipta/pengubah/kameramen/animator/kurator/editor audio visual internasional', NULL, NULL, 'Karya', 20, NULL, NULL);
INSERT INTO unsur_penilaian (ID_UNSUR, ID_KATEGORI, NAMA, BATAS, UNIT, JENIS_BATAS, MAX_KREDIT, BUKTI, KETERANGAN) VALUES (88, 3, 'Pelaksanaan penelitian karya seni sebagai komposer/penulis naskah/sutradara/perancang/pencipta/pengubah/kameramen/animator/kurator/editor audio visual nasional', NULL, NULL, 'Karya', 15, NULL, NULL);
INSERT INTO unsur_penilaian (ID_UNSUR, ID_KATEGORI, NAMA, BATAS, UNIT, JENIS_BATAS, MAX_KREDIT, BUKTI, KETERANGAN) VALUES (89, 3, 'Pelaksanaan penelitian karya seni sebagai komposer/penulis naskah/sutradara/perancang/pencipta/pengubah/kameramen/animator/kurator/editor audio visual lokal', NULL, NULL, 'Karya', 10, NULL, NULL);
INSERT INTO unsur_penilaian (ID_UNSUR, ID_KATEGORI, NAMA, BATAS, UNIT, JENIS_BATAS, MAX_KREDIT, BUKTI, KETERANGAN) VALUES (90, 3, 'Pelaksanaan penelitian kayra seni Sebagai Penata Arstistik/Penata Musik/Penata Rias/PenataBusana/Penata Tari/Penata Lampu/Penata Suara/Penata Panggung/Ilustrator Foto/Kunduktor Internasional', NULL, NULL, 'Pentas', 10, NULL, NULL);
INSERT INTO unsur_penilaian (ID_UNSUR, ID_KATEGORI, NAMA, BATAS, UNIT, JENIS_BATAS, MAX_KREDIT, BUKTI, KETERANGAN) VALUES (91, 3, 'Pelaksanaan penelitian kayra seni Sebagai Penata Arstistik/Penata Musik/Penata Rias/Penata Busana/Penata Tari/Penata Lampu/Penata Suara/Penata Panggung/Ilustrator Foto/Kunduktor nasional', NULL, NULL, 'Pentas', 6, NULL, NULL);
INSERT INTO unsur_penilaian (ID_UNSUR, ID_KATEGORI, NAMA, BATAS, UNIT, JENIS_BATAS, MAX_KREDIT, BUKTI, KETERANGAN) VALUES (92, 3, 'Pelaksanaan penelitian kayra seni Sebagai Penata Arstistik/Penata Musik/Penata Rias/PenataBusana/Penata Tari/Penata Lampu/Penata Suara/Penata Panggung/Ilustrator Foto/Kunduktor lokal', NULL, NULL, 'Pentas', 3, NULL, NULL);
INSERT INTO unsur_penilaian (ID_UNSUR, ID_KATEGORI, NAMA, BATAS, UNIT, JENIS_BATAS, MAX_KREDIT, BUKTI, KETERANGAN) VALUES (93, 3, 'Pelaksanaan penelitian karya seni Sebagai Pemusik/Pengrawit/Penari/Dalang/Pemeran/Pengarah Acara Televisi/Pelaksana Perancangan/Pendisplay Pameran/Pembuat Foto Dokumentasi/Pewarta Foto/Pembawa Acara/Reporter/Redaktur Pelaksana Internasional', NULL, NULL, 'Sajian', 6, NULL, NULL);
INSERT INTO unsur_penilaian (ID_UNSUR, ID_KATEGORI, NAMA, BATAS, UNIT, JENIS_BATAS, MAX_KREDIT, BUKTI, KETERANGAN) VALUES (94, 3, 'Pelaksanaan penelitian karya seni Sebagai Pemusik/Pengrawit/Penari/Dalang/Pemeran/Pengarah Acara Televisi/Pelaksana Perancangan/Pendisplay Pameran/Pembuat Foto Dokumentasi/Pewarta Foto/Pembawa Acara/Reporter/Redaktur Pelaksana nasional', NULL, NULL, 'Sajian', 4, NULL, NULL);
INSERT INTO unsur_penilaian (ID_UNSUR, ID_KATEGORI, NAMA, BATAS, UNIT, JENIS_BATAS, MAX_KREDIT, BUKTI, KETERANGAN) VALUES (95, 3, 'Pelaksanaan penelitian karya seni Sebagai Pemusik/Pengrawit/Penari/Dalang/Pemeran/Pengarah Acara Televisi/Pelaksana Perancangan/ Pendisplay Pameran/Pembuat Foto Dokumentasi/Pewarta Foto/Pembawa Acara/Reporter/Redaktur Pelaksana lokal', NULL, NULL, 'Sajian', 2, NULL, NULL);
INSERT INTO unsur_penilaian (ID_UNSUR, ID_KATEGORI, NAMA, BATAS, UNIT, JENIS_BATAS, MAX_KREDIT, BUKTI, KETERANGAN) VALUES (96, 3, 'Pelaksanaan penelitian karya seni Sebagai Penulis Naskah Drama/Novel Internasional', NULL, NULL, 'Karya', 20, NULL, NULL);
INSERT INTO unsur_penilaian (ID_UNSUR, ID_KATEGORI, NAMA, BATAS, UNIT, JENIS_BATAS, MAX_KREDIT, BUKTI, KETERANGAN) VALUES (97, 3, 'Pelaksanaan penelitian karya seni Sebagai Penulis Naskah Drama/Novel nasional', NULL, NULL, 'Karya', 15, NULL, NULL);
INSERT INTO unsur_penilaian (ID_UNSUR, ID_KATEGORI, NAMA, BATAS, UNIT, JENIS_BATAS, MAX_KREDIT, BUKTI, KETERANGAN) VALUES (98, 3, 'Pelaksanaan penelitian karya seni Sebagai Penulis Naskah Drama/Novel lokal', NULL, NULL, 'Karya', 10, NULL, NULL);
INSERT INTO unsur_penilaian (ID_UNSUR, ID_KATEGORI, NAMA, BATAS, UNIT, JENIS_BATAS, MAX_KREDIT, BUKTI, KETERANGAN) VALUES (99, 3, 'Pelaksanaan penelitian karya satra Sebagai Penulis Buku Kumpulan Cerpen Internasional', NULL, NULL, 'Karya', 20, NULL, NULL);
INSERT INTO unsur_penilaian (ID_UNSUR, ID_KATEGORI, NAMA, BATAS, UNIT, JENIS_BATAS, MAX_KREDIT, BUKTI, KETERANGAN) VALUES (100, 3, 'Pelaksanaan penelitian karya satra Sebagai Penulis Buku Kumpulan Cerpen Nasional', NULL, NULL, 'Karya', 15, NULL, NULL);
INSERT INTO unsur_penilaian (ID_UNSUR, ID_KATEGORI, NAMA, BATAS, UNIT, JENIS_BATAS, MAX_KREDIT, BUKTI, KETERANGAN) VALUES (101, 3, 'Pelaksanaan penelitian karya satra Sebagai Penulis Buku Kumpulan Cerpen Internasional', NULL, NULL, 'Karya', 10, NULL, NULL);
INSERT INTO unsur_penilaian (ID_UNSUR, ID_KATEGORI, NAMA, BATAS, UNIT, JENIS_BATAS, MAX_KREDIT, BUKTI, KETERANGAN) VALUES (102, 3, 'Pelaksanaan penelitian karya satra Sebagai Penulis Buku Kumpulan Puisi Internasional', NULL, NULL, 'Karya', 20, NULL, NULL);
INSERT INTO unsur_penilaian (ID_UNSUR, ID_KATEGORI, NAMA, BATAS, UNIT, JENIS_BATAS, MAX_KREDIT, BUKTI, KETERANGAN) VALUES (103, 3, 'Pelaksanaan penelitian karya satra Sebagai Penulis Buku Kumpulan Cerpen Nasional', NULL, NULL, 'Karya', 15, NULL, NULL);
INSERT INTO unsur_penilaian (ID_UNSUR, ID_KATEGORI, NAMA, BATAS, UNIT, JENIS_BATAS, MAX_KREDIT, BUKTI, KETERANGAN) VALUES (104, 3, 'Pelaksanaan penelitian karya satra Sebagai Penulis Buku Kumpulan Cerpen Lokal', NULL, NULL, 'Karya', 10, NULL, NULL);
INSERT INTO unsur_penilaian (ID_UNSUR, ID_KATEGORI, NAMA, BATAS, UNIT, JENIS_BATAS, MAX_KREDIT, BUKTI, KETERANGAN) VALUES (105, 4, 'Menduduki jabatan pimpinan pada lembaga pemerintahan/pejabat negara yang harus dibebaskan dari jabatan organiknya tiap semester.', NULL, NULL, NULL, 5.5, NULL, NULL);
INSERT INTO unsur_penilaian (ID_UNSUR, ID_KATEGORI, NAMA, BATAS, UNIT, JENIS_BATAS, MAX_KREDIT, BUKTI, KETERANGAN) VALUES (106, 4, 'Melaksanakan pengembangan hasil pendidikan, dan penelitian yang dapat dimanfaatkan oleh masyarakat/ industry setiap program.', NULL, NULL, NULL, 3, NULL, NULL);
INSERT INTO unsur_penilaian (ID_UNSUR, ID_KATEGORI, NAMA, BATAS, UNIT, JENIS_BATAS, MAX_KREDIT, BUKTI, KETERANGAN) VALUES (107, 4, 'Memberi latihan/penyuluhan/ penataran/ceramah pada masyarakat, terjadwal/terprogram : Dalam satu semester atau lebih :  Tingkat Internasional tiap program', NULL, NULL, NULL, 4, NULL, NULL);
INSERT INTO unsur_penilaian (ID_UNSUR, ID_KATEGORI, NAMA, BATAS, UNIT, JENIS_BATAS, MAX_KREDIT, BUKTI, KETERANGAN) VALUES (108, 4, 'Memberi latihan/penyuluhan/ penataran/ceramah pada masyarakat, terjadwal/terprogram : Dalam satu semester atau lebih :  Tingkat Nasional, tiap program', NULL, NULL, NULL, 3, NULL, NULL);
INSERT INTO unsur_penilaian (ID_UNSUR, ID_KATEGORI, NAMA, BATAS, UNIT, JENIS_BATAS, MAX_KREDIT, BUKTI, KETERANGAN) VALUES (109, 4, 'Memberi latihan/penyuluhan/ penataran/ceramah pada masyarakat, terjadwal/terprogram : Dalam satu semester atau lebih :  Tingkat Lokal, tiap program', NULL, NULL, NULL, 2, NULL, NULL);
INSERT INTO unsur_penilaian (ID_UNSUR, ID_KATEGORI, NAMA, BATAS, UNIT, JENIS_BATAS, MAX_KREDIT, BUKTI, KETERANGAN) VALUES (110, 4, 'Memberi latihan/penyuluhan/ penataran/ceramah pada masyarakat, terjadwal/terprogram : Kurang dari satu semester dan minimal satu bulan : Tingkat Internasional tiap program', NULL, NULL, NULL, 3, NULL, NULL);
INSERT INTO unsur_penilaian (ID_UNSUR, ID_KATEGORI, NAMA, BATAS, UNIT, JENIS_BATAS, MAX_KREDIT, BUKTI, KETERANGAN) VALUES (111, 4, 'Memberi latihan/penyuluhan/ penataran/ceramah pada masyarakat, terjadwal/terprogram : Kurang dari satu semester dan minimal satu bulan : Tingkat Nasional, tiap program', NULL, NULL, NULL, 2, NULL, NULL);
INSERT INTO unsur_penilaian (ID_UNSUR, ID_KATEGORI, NAMA, BATAS, UNIT, JENIS_BATAS, MAX_KREDIT, BUKTI, KETERANGAN) VALUES (112, 4, 'Memberi latihan/penyuluhan/ penataran/ceramah pada masyarakat, terjadwal/terprogram : Kurang dari satu semester dan minimal satu bulan : Tingkat Lokal, tiap program', NULL, NULL, NULL, 1, NULL, NULL);
INSERT INTO unsur_penilaian (ID_UNSUR, ID_KATEGORI, NAMA, BATAS, UNIT, JENIS_BATAS, MAX_KREDIT, BUKTI, KETERANGAN) VALUES (113, 4, 'Memberi latihan/penyuluhan/ penataran/ceramah pada masyarakat, terjadwal/terprogram : Kurang dari satu semester dan minimal satu bulan : Insidental, tiap kegiatan/program', NULL, NULL, NULL, 1, NULL, NULL);
INSERT INTO unsur_penilaian (ID_UNSUR, ID_KATEGORI, NAMA, BATAS, UNIT, JENIS_BATAS, MAX_KREDIT, BUKTI, KETERANGAN) VALUES (114, 4, 'Memberi pelayanan kepada masyarakat atau kegiatan lain yang menunjang pelaksanaan tugas pemerintahan dan pembangunan : Berdasarkan bidang keahlian, tiap program', NULL, NULL, NULL, 1.5, NULL, NULL);
INSERT INTO unsur_penilaian (ID_UNSUR, ID_KATEGORI, NAMA, BATAS, UNIT, JENIS_BATAS, MAX_KREDIT, BUKTI, KETERANGAN) VALUES (115, 4, 'Memberi pelayanan kepada masyarakat atau kegiatan lain yang menunjang pelaksanaan tugas pemerintahan dan pembangunan :  Berdasarkan penugasan lembaga terguruan tinggi, tiap program', NULL, NULL, NULL, 1, NULL, NULL);
INSERT INTO unsur_penilaian (ID_UNSUR, ID_KATEGORI, NAMA, BATAS, UNIT, JENIS_BATAS, MAX_KREDIT, BUKTI, KETERANGAN) VALUES (116, 4, 'Memberi pelayanan kepada masyarakat atau kegiatan lain yang menunjang pelaksanaan tugas pemerintahan dan pembangunan :  Berdasarkan fungsi/jabatan tiap program', NULL, NULL, NULL, 0.5, NULL, NULL);
INSERT INTO unsur_penilaian (ID_UNSUR, ID_KATEGORI, NAMA, BATAS, UNIT, JENIS_BATAS, MAX_KREDIT, BUKTI, KETERANGAN) VALUES (117, 4, 'Membuat/menulis karya pengabdian pada masyarakat yang tidak dipublikasikan,tiap karya', NULL, NULL, NULL, 3, NULL, NULL);
INSERT INTO unsur_penilaian (ID_UNSUR, ID_KATEGORI, NAMA, BATAS, UNIT, JENIS_BATAS, MAX_KREDIT, BUKTI, KETERANGAN) VALUES (118, 4, 'Hasil kegiatan pengabdian kepada masyarakat yang dipublikasikan di sebuah berkala/jurnal pengabdian kepada masyarakat atau teknologi tepat guna, merupakan diseminasi dari luaran program kegiatan pengabdian kepada masyarakat, tiap karya', NULL, NULL, NULL, 5, NULL, NULL);
INSERT INTO unsur_penilaian (ID_UNSUR, ID_KATEGORI, NAMA, BATAS, UNIT, JENIS_BATAS, MAX_KREDIT, BUKTI, KETERANGAN) VALUES (119, 4, 'Berperan serta aktif dalam pengelolaan jurnal ilmiah (per tahun)* : Editor/dewan penyunting/dewan redaksi jurnal ilmiah internasional (Diakui satu jurnal)', NULL, NULL, NULL, 1, NULL, NULL);
INSERT INTO unsur_penilaian (ID_UNSUR, ID_KATEGORI, NAMA, BATAS, UNIT, JENIS_BATAS, MAX_KREDIT, BUKTI, KETERANGAN) VALUES (120, 4, 'Berperan serta aktif dalam pengelolaan jurnal ilmiah (per tahun)* :  Editor/dewan penyunting/dewan redaksi jurnal ilmiah nasional (Diakui satu jurnal)', NULL, NULL, NULL, 0.5, NULL, NULL);
INSERT INTO unsur_penilaian (ID_UNSUR, ID_KATEGORI, NAMA, BATAS, UNIT, JENIS_BATAS, MAX_KREDIT, BUKTI, KETERANGAN) VALUES (121, 5, 'Menjadi anggota dalam suatu Panitia/Badan pada Perguruan Tinggi  sebagai Ketua/Wakil Ketua merangkap Anggota, tiap tahun', NULL, NULL, NULL, 3, NULL, NULL);
INSERT INTO unsur_penilaian (ID_UNSUR, ID_KATEGORI, NAMA, BATAS, UNIT, JENIS_BATAS, MAX_KREDIT, BUKTI, KETERANGAN) VALUES (122, 5, 'Menjadi anggota dalam suatu Panitia/Badan pada Perguruan Tinggi sebagai Anggota, tiap tahun', NULL, NULL, NULL, 2, NULL, NULL);
INSERT INTO unsur_penilaian (ID_UNSUR, ID_KATEGORI, NAMA, BATAS, UNIT, JENIS_BATAS, MAX_KREDIT, BUKTI, KETERANGAN) VALUES (123, 5, 'Menjadi anggota panitia/badan pada lembaga pemerintah  panitia pusat, sebagai Ketua/Wakil Ketua, tiap kepanitiaan', NULL, NULL, NULL, 3, NULL, NULL);
INSERT INTO unsur_penilaian (ID_UNSUR, ID_KATEGORI, NAMA, BATAS, UNIT, JENIS_BATAS, MAX_KREDIT, BUKTI, KETERANGAN) VALUES (124, 5, 'Menjadi anggota panitia/badan pada lembaga pemerintah  panitia pusat, sebagai Anggota, tiap kepanitiaan', NULL, NULL, NULL, 2, NULL, NULL);
INSERT INTO unsur_penilaian (ID_UNSUR, ID_KATEGORI, NAMA, BATAS, UNIT, JENIS_BATAS, MAX_KREDIT, BUKTI, KETERANGAN) VALUES (125, 5, 'Menjadi anggota panitia/badan pada lembaga pemerintah panitia daerah, sebagai Ketua/Wakil Ketua, tiap kepanitiaan', NULL, NULL, NULL, 2, NULL, NULL);
INSERT INTO unsur_penilaian (ID_UNSUR, ID_KATEGORI, NAMA, BATAS, UNIT, JENIS_BATAS, MAX_KREDIT, BUKTI, KETERANGAN) VALUES (126, 5, 'Menjadi anggota panitia/badan pada lembaga pemerintah panitia daerah, sebagai Anggota, tiap kepanitiaan', NULL, NULL, NULL, 1, NULL, NULL);
INSERT INTO unsur_penilaian (ID_UNSUR, ID_KATEGORI, NAMA, BATAS, UNIT, JENIS_BATAS, MAX_KREDIT, BUKTI, KETERANGAN) VALUES (127, 5, 'Menjadi anggota organisasi profesi Tingkat Internasional, sebagai :  Pengurus, tiap periode jabatan pengurus merangkap anggota', NULL, NULL, NULL, 2, NULL, NULL);
INSERT INTO unsur_penilaian (ID_UNSUR, ID_KATEGORI, NAMA, BATAS, UNIT, JENIS_BATAS, MAX_KREDIT, BUKTI, KETERANGAN) VALUES (128, 5, 'Menjadi anggota organisasi profesi Tingkat Internasional, sebagai :  Anggota atas permintaan, tiap periode jabatan', NULL, NULL, NULL, 1, NULL, NULL);
INSERT INTO unsur_penilaian (ID_UNSUR, ID_KATEGORI, NAMA, BATAS, UNIT, JENIS_BATAS, MAX_KREDIT, BUKTI, KETERANGAN) VALUES (129, 5, 'Menjadi anggota organisasi profesi Tingkat Internasional, sebagai : Anggota, tiap periode jabatan', NULL, NULL, NULL, 0.5, NULL, NULL);
INSERT INTO unsur_penilaian (ID_UNSUR, ID_KATEGORI, NAMA, BATAS, UNIT, JENIS_BATAS, MAX_KREDIT, BUKTI, KETERANGAN) VALUES (130, 5, 'Menjadi anggota organisasi profesi Tingkat Nasional, sebagai :  Pengurus, tiap periode jabatan', NULL, NULL, NULL, 1.5, NULL, NULL);
INSERT INTO unsur_penilaian (ID_UNSUR, ID_KATEGORI, NAMA, BATAS, UNIT, JENIS_BATAS, MAX_KREDIT, BUKTI, KETERANGAN) VALUES (131, 5, 'Menjadi anggota organisasi profesi Tingkat Nasional, sebagai : Anggota, atas permintaan, tiap periode jabatan', NULL, NULL, NULL, 1, NULL, NULL);
INSERT INTO unsur_penilaian (ID_UNSUR, ID_KATEGORI, NAMA, BATAS, UNIT, JENIS_BATAS, MAX_KREDIT, BUKTI, KETERANGAN) VALUES (132, 5, 'Menjadi anggota organisasi profesi Tingkat Nasional, sebagai : Anggota, tiap periode jabatan', NULL, NULL, NULL, 0.5, NULL, NULL);
INSERT INTO unsur_penilaian (ID_UNSUR, ID_KATEGORI, NAMA, BATAS, UNIT, JENIS_BATAS, MAX_KREDIT, BUKTI, KETERANGAN) VALUES (133, 5, 'Mewakili Perguruan Tinggi/Lembaga Pemerintah duduk dalam Panitia Antar Lembaga, tiap kepanitiaan', NULL, NULL, NULL, 1, NULL, NULL);
INSERT INTO unsur_penilaian (ID_UNSUR, ID_KATEGORI, NAMA, BATAS, UNIT, JENIS_BATAS, MAX_KREDIT, BUKTI, KETERANGAN) VALUES (134, 5, 'Menjadi anggota delegasi Nasional ke pertemuan Internasional Sebagai Ketua delegasi, tiap kegiatan', NULL, NULL, NULL, 3, NULL, NULL);
INSERT INTO unsur_penilaian (ID_UNSUR, ID_KATEGORI, NAMA, BATAS, UNIT, JENIS_BATAS, MAX_KREDIT, BUKTI, KETERANGAN) VALUES (135, 5, 'Menjadi anggota delegasi Nasional ke pertemuan Internasional Sebagai Anggota, tiap kegiatan', NULL, NULL, NULL, 2, NULL, NULL);
INSERT INTO unsur_penilaian (ID_UNSUR, ID_KATEGORI, NAMA, BATAS, UNIT, JENIS_BATAS, MAX_KREDIT, BUKTI, KETERANGAN) VALUES (136, 5, 'Berperan serta aktif dalam pertemuan ilmiah tingkat Internasional/Nasional/Regional sebagai : Ketua, tiap kegiatan', NULL, NULL, NULL, 3, NULL, NULL);
INSERT INTO unsur_penilaian (ID_UNSUR, ID_KATEGORI, NAMA, BATAS, UNIT, JENIS_BATAS, MAX_KREDIT, BUKTI, KETERANGAN) VALUES (137, 5, 'Berperan serta aktif dalam pertemuan ilmiah Tingkat Internasional/Nasional/Regional sebagai : Anggota/peserta, tiap kegiatan', NULL, NULL, NULL, 2, NULL, NULL);
INSERT INTO unsur_penilaian (ID_UNSUR, ID_KATEGORI, NAMA, BATAS, UNIT, JENIS_BATAS, MAX_KREDIT, BUKTI, KETERANGAN) VALUES (138, 5, 'Berperan serta aktif dalam pertemuan ilmiah Di lingkungan Perguruan Tinggi sebagai :  Ketua, tiap kegiatan', NULL, NULL, NULL, 2, NULL, NULL);
INSERT INTO unsur_penilaian (ID_UNSUR, ID_KATEGORI, NAMA, BATAS, UNIT, JENIS_BATAS, MAX_KREDIT, BUKTI, KETERANGAN) VALUES (139, 5, 'Berperan serta aktif dalam pertemuan ilmiah Di lingkungan Perguruan Tinggi sebagai :  Anggota/peserta, tiap kegiatan', NULL, NULL, NULL, 1, NULL, NULL);
INSERT INTO unsur_penilaian (ID_UNSUR, ID_KATEGORI, NAMA, BATAS, UNIT, JENIS_BATAS, MAX_KREDIT, BUKTI, KETERANGAN) VALUES (140, 5, 'Mendapat tanda jasa/penghargaan : Penghargaan/tanda jasa Satya lencana 30 tahun', NULL, NULL, NULL, 3, NULL, NULL);
INSERT INTO unsur_penilaian (ID_UNSUR, ID_KATEGORI, NAMA, BATAS, UNIT, JENIS_BATAS, MAX_KREDIT, BUKTI, KETERANGAN) VALUES (141, 5, 'Mendapat tanda jasa/penghargaan : Penghargaan/tanda jasa Satya lencana 20 tahun', NULL, NULL, NULL, 2, NULL, NULL);
INSERT INTO unsur_penilaian (ID_UNSUR, ID_KATEGORI, NAMA, BATAS, UNIT, JENIS_BATAS, MAX_KREDIT, BUKTI, KETERANGAN) VALUES (142, 5, 'Mendapat tanda jasa/penghargaan : Penghargaan/tanda jasa Satya lencana 10 tahun', NULL, NULL, NULL, 1, NULL, NULL);
INSERT INTO unsur_penilaian (ID_UNSUR, ID_KATEGORI, NAMA, BATAS, UNIT, JENIS_BATAS, MAX_KREDIT, BUKTI, KETERANGAN) VALUES (143, 5, 'Mendapat tanda jasa/penghargaan : Tingkat Internasional, tiap tanda jasa/penghargaan', NULL, NULL, NULL, 5, NULL, NULL);
INSERT INTO unsur_penilaian (ID_UNSUR, ID_KATEGORI, NAMA, BATAS, UNIT, JENIS_BATAS, MAX_KREDIT, BUKTI, KETERANGAN) VALUES (144, 5, 'Mendapat tanda jasa/penghargaan : Tingkat Nasional, tiap tanda jasa/penghargaan', NULL, NULL, NULL, 3, NULL, NULL);
INSERT INTO unsur_penilaian (ID_UNSUR, ID_KATEGORI, NAMA, BATAS, UNIT, JENIS_BATAS, MAX_KREDIT, BUKTI, KETERANGAN) VALUES (145, 5, 'Mendapat tanda jasa/penghargaan :  Tingkat Daerah/Lokal, tiap tanda jasa/penghargaan', NULL, NULL, NULL, 1, NULL, NULL);
INSERT INTO unsur_penilaian (ID_UNSUR, ID_KATEGORI, NAMA, BATAS, UNIT, JENIS_BATAS, MAX_KREDIT, BUKTI, KETERANGAN) VALUES (146, 5, 'Menulis buku pelajaran SLTA ke bawah yang diterbitkan dan diedarkan secara nasional :  Buku SMTA atau setingkat, tiap buku', NULL, NULL, NULL, 5, NULL, NULL);
INSERT INTO unsur_penilaian (ID_UNSUR, ID_KATEGORI, NAMA, BATAS, UNIT, JENIS_BATAS, MAX_KREDIT, BUKTI, KETERANGAN) VALUES (147, 5, 'Menulis buku pelajaran SLTA ke bawah yang diterbitkan dan diedarkan secara nasional :  Buku SMTP atau setingkat, tiap buku', NULL, NULL, NULL, 5, NULL, NULL);
INSERT INTO unsur_penilaian (ID_UNSUR, ID_KATEGORI, NAMA, BATAS, UNIT, JENIS_BATAS, MAX_KREDIT, BUKTI, KETERANGAN) VALUES (148, 5, 'Menulis buku pelajaran SLTA ke bawah yang diterbitkan dan diedarkan secara nasional :   Buku SD atau setingkat, tiap buku', NULL, NULL, NULL, 5, NULL, NULL);
INSERT INTO unsur_penilaian (ID_UNSUR, ID_KATEGORI, NAMA, BATAS, UNIT, JENIS_BATAS, MAX_KREDIT, BUKTI, KETERANGAN) VALUES (149, 5, 'Mempunyai prestasi di bidang olahraga/ Humaniora : Tingkat Internasional, tiap piagam/medali', NULL, NULL, NULL, 5, NULL, NULL);
INSERT INTO unsur_penilaian (ID_UNSUR, ID_KATEGORI, NAMA, BATAS, UNIT, JENIS_BATAS, MAX_KREDIT, BUKTI, KETERANGAN) VALUES (150, 5, 'Mempunyai prestasi di bidang olahraga/ Humaniora : Tingkat Nasional, tiap piagam/medali', NULL, NULL, NULL, 3, NULL, NULL);
INSERT INTO unsur_penilaian (ID_UNSUR, ID_KATEGORI, NAMA, BATAS, UNIT, JENIS_BATAS, MAX_KREDIT, BUKTI, KETERANGAN) VALUES (151, 5, 'Mempunyai prestasi di bidang olahraga/ Humaniora : Tingkat Daerah/Lokal, tiap piagam/medali', NULL, NULL, NULL, 1, NULL, NULL);
INSERT INTO unsur_penilaian (ID_UNSUR, ID_KATEGORI, NAMA, BATAS, UNIT, JENIS_BATAS, MAX_KREDIT, BUKTI, KETERANGAN) VALUES (152, 5, 'Keanggotaan dalam tim penilai jabatan akademik dosen', NULL, NULL, NULL, 0.5, NULL, NULL);
